name: 'action-release-notes-notifier'
description: Parses the most recent commit for changes to variables.
inputs:
  environment:
    description: 'Name of environment'
    required: true
  file-pattern:
    description: 'Pattern to match files'
    required: true
  organization:
    description: 'GitHub organization name'
    required: true
  slack-webhook:
    description: 'Slack Webhook URL'
    required: true
  token:
    description: 'GitHub Token or PAT'
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'
    - run: make install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: python ${{ github.action_path }}/main.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        FILE_PATTERN: ${{ inputs.file-pattern }}
        ORGANIZATION: ${{ inputs.organization }}
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        TOKEN: ${{ inputs.token }}
