name: 'action-release-notes-notifier'
description: Parses the most recent commit for changes to variables.
inputs:
  organization:
    description: 'GitHub organization name'
    required: true
  token:
    description: 'GitHub Token or PAT'
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: make install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: python ${{ github.action_path }}/main.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        TOKEN: ${{ inputs.token }}
        ORGANIZATION: ${{ inputs.organization }}
