name: 'action-release-notes-notifier'
description: A GitHub Action which sends notifications to Slack with the release notes of new releases.
inputs:
  environment:
    description: 'Name of the environment'
    required: true
  file-pattern:
    description: 'Regex pattern to filter files'
    required: true
  organization:
    description: 'GitHub organization name'
    required: true
  slack-webhook:
    description: 'Slack webhook URL to send notifications'
    required: true
  tag-name:
    description: 'Tag to add to the source repositories'
    required: false
    default: ''
  token:
    description: 'GitHub Token or PAT'
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - run: 'cp ${{ github.action_path }}/requirements.txt .'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: make install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: python ${{ github.action_path }}/main.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        FILE_PATTERN: ${{ inputs.file-pattern }}
        ORGANIZATION: ${{ inputs.organization }}
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        TOKEN: ${{ inputs.token }}
        TAG_NAME: ${{ inputs.tag-name }}
